name: uberdriver
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  cloud_firestore: ^5.4.2
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  flutter_geofire: ^2.0.3
  flutter_styled_toast: ^2.2.1
  font_awesome_flutter: ^10.4.0
  geolocator: ^13.0.1
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  page_transition: ^2.1.0
  persistent_bottom_nav_bar_2: ^5.0.3
  pin_code_fields: ^8.0.1
  google_maps_flutter: ^2.3.0
  firebase_messaging: ^15.1.3
  http: ^0.13.6
  firebase_database: ^11.1.4
  provider: ^6.1.2
  flutter_swipe_button: ^2.1.1+1
  sizer: ^2.0.15
  just_audio: ^0.9.36
  flutter_polyline_points: ^1.0.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/categories/
    - assets/images/splashScreenImage/
  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf
